---
- name: K8s cluster with three nodes 
  hosts: 'all'
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: prepare-environment, tags: ["prepare-environment"]}
    - { role: k8s-cluster, tags: ["k8s-cluster"]}

...    
