---
- name: Load kernel modules
  shell: sudo modprobe br_netfilter ip_vs_rr ip_vs_wrr ip_vs_sh nf_conntrack_ipv4 ip_vs
  tags: load-kernel-modules

- name: Apply pod network - weave
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when: "'k8s-manager01' in inventory_hostname"
  tags: apply-weave

...
