---
- name: Create kernel modules file
  file:
    path: /etc/modules-load.d/k8s.conf
    state: touch
  tags: create-kernel-modules-file

- name: Configuration kernel module 
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
      br_netfilter
      ip_vs
      ip_vs_rr
      ip_vs_sh
      ip_vs_wrr
      nf_conntrack_ipv4
  tags: kernel-modules

- name: Install Docker 
  shell: curl -fsSL https://get.docker.com | bash
  tags: install-docker

- name: Create Docker daemon reload file
  file:
    path: /etc/docker/daemon.json
    state: touch
  tags: create-docker-daemon-file

- name: Configure Docker daemon reload
  blockinfile:
    path: /etc/docker/daemon.json
    block: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
          "overlay2.override_kernel_check=true"
        ]
      }
  tags: conf-docker-daemon

- name: Docker service directory
  shell: 'mkdir -p /etc/systemd/system/docker.service.d'
  tags: docker-service-dir

- name: Daemon reload
  shell: 'systemctl daemon-reload'
  tags: daemon-reload

- name: Restart Docker service
  service:
    name: docker
    state: restarted
  tags: restart-docker-service

- name: Update repo
  apt:
    update_cache: yes
  tags: update

- name: Install packages needed to use the Kubernetes apt repository
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - curl
    state: latest
  tags: install-packages

- name: Download the Google Cloud public signing ke
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  tags: download-key

- name: Add the Kubernetes apt repository
  shell: echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
  tags: add-k8s-apt-repo

- name: Update Repository
  apt:
    update_cache: yes
  tags: update

- name: Install kubelet, kubeadm and kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest
  tags: install-packages

- name: Disable swap
  shell: swapoff -a
  tags: Disable swap

- name: Download images
  shell: kubeadm config images pull
  when: "'k8s-manager01' in inventory_hostname"
  tags: download-images

- name: Init cluster
  shell: kubeadm init
  when: "'k8s-manager01' in inventory_hostname"
  tags: init-cluster
  
- name: Registry cluster token
  shell: kubeadm token list | grep -i "kubeadm init" | cut -d ' ' -f1
  when: "'k8s-manager01' in inventory_hostname"
  register: k8s_token
  changed_when: True
  tags: registry-token

- name: Registry Ca Hash
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  when: "'k8s-manager01' in inventory_hostname"
  register: k8s_ca_hash
  tags: registry-hash

- name: Add token, hash and certificate key in a dummy host
  add_host:
    name: "K8S_TOKEN_HOLDER"
    token: "{{ k8s_token.stdout }}"
    hash: "{{ k8s_ca_hash.stdout }}"
  tags: dummy-host

- name: Print token
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - the token is {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"
  tags: print-token

- name: Print hash
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - the CA Hash is {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"
  tags: print-hash

- name: Create kube dir
  file:
    path: ~/.kube
    state: directory
    mode: 0750
  when: "'k8s-manager01' in inventory_hostname"
  tags: create-kube-dir

- name: Link k8s admin conf
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
  changed_when: True
  when: "'manager01' in inventory_hostname"
  tags: copy-k8s-admin-conf

- name: Change owner
  shell: 'chown $(id -u):$(id -g) $HOME/.kube/config'
  when: "'manager01' in inventory_hostname"
  tags: change-owner

...  
